/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wh7tEveR
 */
public class LibraryForm extends javax.swing.JFrame {
    private Connection conn;
private DefaultTableModel modelSach;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibraryForm.class.getName());

    /**
     * Creates new form LibraryForm
     */
    public LibraryForm() {
                initComponents();

        setTitle("Chương trình Quản lý Sách");
    setLocationRelativeTo(null);
    conn = DBConnection.getConnection();
    if (conn == null) {
         JOptionPane.showMessageDialog(this, "Không thể kết nối đến CSDL. Vui lòng kiểm tra cấu hình.", "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
            }
    initTableSach();
    loadDataToTableSach();
    addTableSachListener();
    }
private void initTableSach() {
    modelSach = new DefaultTableModel();
    modelSach.setColumnIdentifiers(new String[]{"Mã Sách", "Tên Sách", "Tác Giả", "Thể Loại", "Số Lượng"});
    tblSach.setModel(modelSach);
}

private void loadDataToTableSach() {
    if (conn == null) return;
    modelSach.setRowCount(0);
    String sql = "SELECT * FROM Sach ORDER BY MaSach";

    try (Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {
        while (rs.next()) {
            Vector<Object> row = new Vector<>();
            row.add(rs.getString("MaSach"));
            row.add(rs.getString("TenSach"));
            row.add(rs.getString("TacGia"));
            row.add(rs.getString("TheLoai"));
            row.add(rs.getInt("SoLuong"));
            modelSach.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu Sách: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

private void resetFormSach() {
    txtMaSach.setText("");
    txtTenSach.setText("");
    txtTacGia.setText("");
    txtTheLoai.setText("");
    txtSoLuong.setText("");
    txtMaSach.setEditable(true);
    tblSach.clearSelection();
}

private void addTableSachListener() {
    tblSach.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
        if (!e.getValueIsAdjusting() && tblSach.getSelectedRow() != -1) {
            int row = tblSach.getSelectedRow();
            txtMaSach.setText(modelSach.getValueAt(row, 0).toString());
            txtTenSach.setText(modelSach.getValueAt(row, 1).toString());
            txtTacGia.setText(modelSach.getValueAt(row, 2) != null ? modelSach.getValueAt(row, 2).toString() : "");
            txtTheLoai.setText(modelSach.getValueAt(row, 3) != null ? modelSach.getValueAt(row, 3).toString() : "");
            txtSoLuong.setText(modelSach.getValueAt(row, 4).toString());
            txtMaSach.setEditable(false);
        }
    });
}
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSachInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtTheLoai = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        pnlSachButtons = new javax.swing.JPanel();
        btnHienThi = new javax.swing.JButton();
        btnThemSach = new javax.swing.JButton();
        btnSuaSach = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        btnResetSach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlSachInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sách"));

        jLabel1.setText("Mã Sách");

        jLabel2.setText("Tên Sách");

        jLabel3.setText("Tác Giả");

        jLabel4.setText("Thể Loại");

        jLabel5.setText("Số Lượng");

        pnlSachButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 5));

        btnHienThi.setText("HIỂN THỊ");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });
        pnlSachButtons.add(btnHienThi);

        btnThemSach.setText("THÊM");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });
        pnlSachButtons.add(btnThemSach);

        btnSuaSach.setText("CẬP NHẬT");
        btnSuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSachActionPerformed(evt);
            }
        });
        pnlSachButtons.add(btnSuaSach);

        btnXoaSach.setText("XÓA");
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });
        pnlSachButtons.add(btnXoaSach);

        btnResetSach.setText("RESET");
        btnResetSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSachActionPerformed(evt);
            }
        });
        pnlSachButtons.add(btnResetSach);

        javax.swing.GroupLayout pnlSachInfoLayout = new javax.swing.GroupLayout(pnlSachInfo);
        pnlSachInfo.setLayout(pnlSachInfoLayout);
        pnlSachInfoLayout.setHorizontalGroup(
            pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSachInfoLayout.createSequentialGroup()
                .addGroup(pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSachInfoLayout.createSequentialGroup()
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSachInfoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSachInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSachInfoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(pnlSachInfoLayout.createSequentialGroup()
                .addComponent(pnlSachButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSachInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtMaSach, txtSoLuong, txtTacGia, txtTenSach, txtTheLoai});

        pnlSachInfoLayout.setVerticalGroup(
            pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSachInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlSachInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(pnlSachButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pnlSachInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMaSach, txtSoLuong, txtTacGia, txtTenSach, txtTheLoai});

        jPanel1.add(pnlSachInfo, java.awt.BorderLayout.PAGE_START);

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSach);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Chưa kết nối CSDL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String maSach = txtMaSach.getText().trim();
        String tenSach = txtTenSach.getText().trim();
        String tacGia = txtTacGia.getText().trim();
        String theLoai = txtTheLoai.getText().trim();

        if (maSach.isEmpty() || tenSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã sách và Tên sách không được để trống!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int soLuong;
        try {
            String soLuongText = txtSoLuong.getText().trim();
             if (soLuongText.isEmpty()) {
                soLuong = 0;
            } else {
                soLuong = Integer.parseInt(soLuongText);
                 if (soLuong < 0) {
                     JOptionPane.showMessageDialog(this, "Số lượng không được âm!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                     return;
                 }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO Sach(MaSach, TenSach, TacGia, TheLoai, SoLuong) VALUES(?, ?, ?, ?, ?)";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, maSach);
            pstmt.setString(2, tenSach);
            pstmt.setString(3, tacGia);
            pstmt.setString(4, theLoai);
            pstmt.setInt(5, soLuong);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Thêm sách thành công!");
                loadDataToTableSach();
                resetFormSach();
            }
        } catch (SQLException e) {
            if (e.getSQLState().equals("23505")) {
                JOptionPane.showMessageDialog(this, "Mã sách đã tồn tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                 JOptionPane.showMessageDialog(this, "Lỗi khi thêm sách: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                 e.printStackTrace();
            }
        } catch (NullPointerException e) {
             JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL khi thêm. Vui lòng kiểm tra lại.", "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
             e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnSuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSachActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Chưa kết nối CSDL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String maSach = txtMaSach.getText().trim();
        if (maSach.isEmpty() || txtMaSach.isEditable()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một cuốn sách từ bảng để cập nhật.", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tenSach = txtTenSach.getText().trim();
        String tacGia = txtTacGia.getText().trim();
        String theLoai = txtTheLoai.getText().trim();
        int soLuong;

        try {
            String soLuongText = txtSoLuong.getText().trim();
             if (soLuongText.isEmpty()) {
                soLuong = 0;
            } else {
                soLuong = Integer.parseInt(soLuongText);
                 if (soLuong < 0) {
                     JOptionPane.showMessageDialog(this, "Số lượng không được âm!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                     return;
                 }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE Sach SET TenSach = ?, TacGia = ?, TheLoai = ?, SoLuong = ? WHERE MaSach = ?";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, tenSach);
            pstmt.setString(2, tacGia);
            pstmt.setString(3, theLoai);
            pstmt.setInt(4, soLuong);
            pstmt.setString(5, maSach);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadDataToTableSach();
                resetFormSach();
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách để cập nhật (có thể đã bị xóa).", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                 resetFormSach();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật sách: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (NullPointerException e) {
             JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL khi cập nhật. Vui lòng kiểm tra lại.", "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
             e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaSachActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Chưa kết nối CSDL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String maSach = txtMaSach.getText().trim();
         if (maSach.isEmpty() || txtMaSach.isEditable()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một cuốn sách từ bảng để xoá.", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xoá sách '" + maSach + "' không?",
                "Xác nhận xoá",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM Sach WHERE MaSach = ?";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, maSach);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Xoá sách thành công!");
                loadDataToTableSach();
                resetFormSach();
            } else {
                 JOptionPane.showMessageDialog(this, "Không tìm thấy sách để xoá (có thể đã bị xóa trước đó).", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                 resetFormSach();
            }
        } catch (SQLException e) {
            if (e.getSQLState().equals("23503")) {
                 JOptionPane.showMessageDialog(this, "Không thể xoá sách này! Sách đang được độc giả mượn.", "Lỗi Ràng Buộc", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi xoá sách: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                 e.printStackTrace();
            }
        } catch (NullPointerException e) {
             JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL khi xóa. Vui lòng kiểm tra lại.", "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
             e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnResetSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSachActionPerformed
        resetFormSach();
    }//GEN-LAST:event_btnResetSachActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        loadDataToTableSach();
    }//GEN-LAST:event_btnHienThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibraryForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnResetSach;
    private javax.swing.JButton btnSuaSach;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSachButtons;
    private javax.swing.JPanel pnlSachInfo;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    // End of variables declaration//GEN-END:variables
}
